[platformio]
default_envs = blind_esp8266

; --- GLOBAL ENVIROMENT ---

[env]
framework = arduino
build_flags =
    -Os
    -I include
    -I include/logic
    -I include/network
    -I include/settings
lib_deps =
    ;knolleary/PubSubClient @ ^2.8
    vshymanskyy/Preferences @ ^2.2.2

; --- HARDWARE ---

[esp8266]
platform = espressif8266
board = esp01_1m
board_build.ldscript = eagle.flash.1m256.ld
board_build.flash_mode = dout
build_flags = 
    ${env.build_flags}
    -I include/hardware/esp8266
    -D DEVICE_HARDWARE_ESP8266

[bk7231n]
platform = libretiny
board = generic-bk7231n-qfn32-tuya
build_flags = 
    ${env.build_flags}
    -I include/hardware/bk7231n
    -D DEVICE_HARDWARE_BK7231N



; --- ENVIROMENTS ---

; Blind on ESP8266
[env:blind_esp8266]
extends = esp8266
build_flags = 
    ${esp8266.build_flags}
    -D DEVICE_TYPE_BLIND

; Blind on BK7231N
[env:blind_bk7231n]
extends = bk7231n
build_flags = 
    ${bk7231n.build_flags}
    -D DEVICE_TYPE_BLIND

; Light on BK7231N
[env:light_bk7231]
extends = bk7231n
build_flags = 
    ${bk7231n.build_flags}
    -D DEVICE_TYPE_LIGHT